/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exampol;

/**
 *
 * @author MiguelGz
 */
public class TienditaPepe extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public TienditaPepe() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Prototaip");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        txtext4 = new javax.swing.JLabel();
        txtext3 = new javax.swing.JLabel();
        txtext2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista1 = new javax.swing.JList<>();
        textito1 = new javax.swing.JLabel();
        boton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtext = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblpantalla = new javax.swing.JLabel();
        lblcamara = new javax.swing.JLabel();
        lblprocesador = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.gray);
        setMaximumSize(new java.awt.Dimension(1000, 650));
        setMinimumSize(new java.awt.Dimension(1000, 650));
        getContentPane().setLayout(null);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "    Selecciona el Plan", "Claro Max 99", "Claro Max 149", "Claro Max 189", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(250, 350, 154, 57);

        txtext4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtext4);
        txtext4.setBounds(630, 460, 120, 50);

        txtext3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtext3);
        txtext3.setBounds(470, 360, 110, 51);

        txtext2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtext2);
        txtext2.setBounds(474, 462, 130, 60);

        lista1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lista1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "     Samsung Galaxy S6\t", "     Iphone 6 Plush", "     Nosequemas" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lista1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lista1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(lista1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 120, 162, 310);

        textito1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textito1.setText("  TELEFONO MOVIL");
        textito1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(textito1);
        textito1.setBounds(337, 36, 219, 47);

        boton1.setText("Seleccionar Dispositivo");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        getContentPane().add(boton1);
        boton1.setBounds(27, 462, 162, 50);

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 2, 18)); // NOI18N
        jLabel1.setText("Tienda Claro");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 170, 63);

        txtext.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtext);
        txtext.setBounds(620, 360, 140, 51);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\MiguelGz\\Desktop\\11.jpg")); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setIconTextGap(-3);
        jButton1.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\MiguelGz\\Desktop\\12.jpg")); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\MiguelGz\\Desktop\\13.jpg")); // NOI18N
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 470, 91, 83);

        lblpantalla.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblpantalla.setText("   -");
        getContentPane().add(lblpantalla);
        lblpantalla.setBounds(340, 150, 46, 45);

        lblcamara.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblcamara.setText("     -");
        getContentPane().add(lblcamara);
        lblcamara.setBounds(500, 150, 69, 46);

        lblprocesador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblprocesador.setText("    -");
        getContentPane().add(lblprocesador);
        lblprocesador.setBounds(660, 150, 55, 46);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("¡ELIGE EL MEJOR PLAN PARA TI !");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 280, 616, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Pantalla");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(290, 210, 61, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Camara");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(460, 210, 59, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Procesador");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(620, 210, 86, 22);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\MiguelGz\\Desktop\\caramira.jpg")); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(430, 140, 54, 63);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\MiguelGz\\Desktop\\telefono.jpg")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(270, 130, 56, 75);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\MiguelGz\\Desktop\\procesdo.jpg")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(600, 150, 56, 56);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\MiguelGz\\Desktop\\Untitled.jpg")); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, -20, 940, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        int item =jComboBox1.getSelectedIndex();
        
       
    switch (item){
         case 0:
            txtext.setText("");
            txtext4.setText("");
            txtext2.setText("");
            txtext3.setText("");
            break;
        
        case 1:
            txtext.setText("Minutos: "
                    + "Ilimitados  ");
            txtext4.setText("Mensajes: "
                    + "Ilimitados");
            txtext2.setText("Interned: "
                    + " 4 GB");
            txtext3.setText("Etc");
             txtext3.setText("Precio:"
                    + "3400");
            break;
         case 2:
            txtext.setText("Minutos: "
                    + "Ilimitados");
            txtext4.setText("Mensajes: "
                    + "Ilimitados");
            txtext2.setText("Interned: "
                    + "Ilimitados");
            txtext3.setText("Etc");
             txtext3.setText("Precio:"
                    + "2900");
            break;
          case 3:
             txtext.setText("Minutos: "
                     + "Ilimitados ");
            txtext4.setText("Mensajes: "
                    + "Ilimitados");
            txtext2.setText("Interned: "
                    + "Ilimitados");
            txtext3.setText("Precio:"
                    + "9999");
            break;
              
    
    }
    
    
    
        
  


    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void lista1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lista1AncestorAdded
    
           
    
   
        
    }//GEN-LAST:event_lista1AncestorAdded

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
    int item =lista1.getSelectedIndex();
        textito1.setText(String.valueOf(lista1.getSelectedValue()));
        
        switch (item){
            case 0:
                lblcamara.setText("8 MP");
                lblpantalla.setText("8.3");
                lblprocesador.setText("4 GB");
                        
                break;
                case 1:
                lblcamara.setText("7 MP");
                 lblpantalla.setText("7.3");
                lblprocesador.setText("3 GB");
                        
                break;
                case 2:
                lblcamara.setText("6 MP");
                 lblpantalla.setText("6.3");
                lblprocesador.setText("2 GB");
                        
                break;
            
        }
     
// TODO add your handling code here:
    }//GEN-LAST:event_boton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     Pago paga= new Pago();
     paga.setVisible(true);
     dispose();
     
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TienditaPepe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TienditaPepe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TienditaPepe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TienditaPepe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TienditaPepe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcamara;
    private javax.swing.JLabel lblpantalla;
    private javax.swing.JLabel lblprocesador;
    private javax.swing.JList<String> lista1;
    private javax.swing.JLabel textito1;
    private javax.swing.JLabel txtext;
    private javax.swing.JLabel txtext2;
    private javax.swing.JLabel txtext3;
    private javax.swing.JLabel txtext4;
    // End of variables declaration//GEN-END:variables

    
}
